/* Single source of truth for the dashboard. Update business data here. */
const SPCX_CONFIG = {
  ticker: "SPCX",
  companyName: "Space Exploration Technologies Corp. (SpaceX)",
  exchange: "Nasdaq Global Select Market / Nasdaq Texas",
  country: "United States",
  verified: true,
  warning: "ราคาตลาดเชื่อมจาก Yahoo Finance; ตัวชี้วัดธุรกิจควรติดตามจากเอกสารบริษัทและผลประกอบการรายไตรมาส",
};

const companies = [
  {
    ticker: "ASML",
    marketSymbol: "ASML",
    name: "ASML Holding",
    shortName: "ASML",
    layer: 1,
    category: "Semiconductor",
    position: "Semiconductor Equipment",
    summary: "ผู้ผลิตเครื่อง EUV และ High-NA EUV ที่จำเป็นต่อการผลิตชิปขั้นสูง",
    revenue: ["EUV systems", "DUV systems", "Installed Base Management"],
    customers: ["TSMC", "Samsung", "Intel"],
    dependencies: ["Customer fab capex", "Supply chain capacity", "Export licenses"],
    growthDrivers: ["High-NA adoption", "EUV intensity per wafer", "Advanced-node fab expansion"],
    risks: ["Export restrictions ไปจีน", "Bookings ผันผวน", "Customer concentration"],
    metrics: ["Net bookings", "EUV shipments", "High-NA adoption", "Customer capex", "China exposure", "Guidance ปีถัดไป"],
    goodImpact: [
      { ticker: "TSMC", level: "Medium", note: "สะท้อนความเชื่อมั่นต่อการลงทุนกำลังผลิต" },
      { ticker: "NVDA", level: "Indirect", note: "บวกต่อ supply capacity ระยะยาว" },
      { ticker: "AVGO", level: "Indirect", note: "บวกต่อ custom silicon ecosystem" },
    ],
    badImpact: [
      { ticker: "TSMC", level: "Medium", note: "อาจสะท้อนการชะลอ capex" },
      { ticker: "NVDA", level: "Indirect", note: "เสี่ยงต่อกำลังผลิตในอนาคต" },
    ],
  },
  {
    ticker: "TSMC",
    marketSymbol: "TSM",
    name: "Taiwan Semiconductor Manufacturing",
    shortName: "TSMC",
    layer: 2,
    category: "Semiconductor",
    position: "Semiconductor Manufacturing",
    summary: "ศูนย์กลางการรับผลิตชิป AI ขั้นสูงและตัวชี้วัด demand จริงจากลูกค้า",
    revenue: ["Wafer fabrication", "Advanced nodes", "Advanced packaging"],
    customers: ["NVIDIA", "Apple", "Broadcom", "AMD"],
    dependencies: ["ASML equipment", "AI accelerator demand", "Taiwan operations"],
    growthDrivers: ["HPC mix", "3 nm / 2 nm demand", "CoWoS expansion"],
    risks: ["Taiwan geopolitical risk", "Capex intensity", "Customer concentration"],
    metrics: ["HPC growth", "Utilization rate", "3 nm และ 2 nm demand", "Advanced packaging / CoWoS", "Gross margin", "Capex", "AI accelerator demand"],
    goodImpact: [
      { ticker: "NVDA", level: "Direct", note: "ยืนยันความต้องการ GPU และ packaging" },
      { ticker: "AVGO", level: "Direct", note: "ยืนยัน custom ASIC demand" },
      { ticker: "ASML", level: "Medium", note: "โอกาสสั่งเครื่องจักรเพิ่ม" },
      { ticker: "AAPL", level: "Medium", note: "ขึ้นกับ demand ชิปอุปกรณ์" },
    ],
    badImpact: [
      { ticker: "NVDA", level: "Direct", note: "เสี่ยงต่อคำสั่งผลิตและ supply" },
      { ticker: "AVGO", level: "Direct", note: "เสี่ยงต่อ ASIC cycle" },
      { ticker: "ASML", level: "Medium", note: "capex อาจชะลอ" },
    ],
  },
  {
    ticker: "NVDA",
    marketSymbol: "NVDA",
    name: "NVIDIA",
    shortName: "NVIDIA",
    layer: 3,
    category: "Semiconductor",
    position: "AI Chips and Networking",
    summary: "แพลตฟอร์ม GPU, networking, CUDA และระบบ Data Center สำหรับ AI",
    revenue: ["Data Center", "Gaming", "Networking and systems"],
    customers: ["Microsoft", "Alphabet", "Amazon", "AI labs"],
    dependencies: ["TSMC", "HBM suppliers", "Hyperscaler capex"],
    growthDrivers: ["Blackwell ramp", "Inference demand", "CUDA ecosystem"],
    risks: ["China export restrictions", "Custom ASIC competition", "Supply constraints"],
    metrics: ["Data Center revenue", "Blackwell shipments", "GPU demand", "Gross margin", "Supply constraints", "Hyperscaler capex", "China exposure"],
    goodImpact: [
      { ticker: "TSMC", level: "Direct", note: "คำสั่งผลิต GPU และ advanced packaging เพิ่ม" },
      { ticker: "ASML", level: "Indirect", note: "หนุนการลงทุนกำลังผลิตระยะยาว" },
      { ticker: "AVGO", level: "Medium", note: "AI infrastructure sentiment ดีขึ้น" },
      { ticker: "MSFT", level: "Medium", note: "AI demand แข็งแรง แต่ต้องดูต้นทุน capex" },
      { ticker: "GOOGL", level: "Medium", note: "AI demand แข็งแรง แต่ต้องดูต้นทุน capex" },
      { ticker: "AMZN", level: "Medium", note: "AI demand แข็งแรง แต่ต้องดูต้นทุน capex" },
    ],
    badImpact: [
      { ticker: "TSMC", level: "Direct", note: "คำสั่งผลิตและ CoWoS อาจชะลอ" },
      { ticker: "ASML", level: "Indirect", note: "capex cycle อาจอ่อนตัวภายหลัง" },
      { ticker: "AVGO", level: "Medium", note: "กดดัน AI infrastructure sentiment" },
    ],
  },
  {
    ticker: "AVGO",
    marketSymbol: "AVGO",
    name: "Broadcom",
    shortName: "Broadcom",
    layer: 3,
    category: "Semiconductor",
    position: "AI Chips and Networking",
    summary: "ออกแบบ custom AI ASIC และ networking chips สำหรับ AI Data Center",
    revenue: ["Semiconductor solutions", "AI networking", "VMware infrastructure software"],
    customers: ["Hyperscalers", "Enterprise IT", "Network operators"],
    dependencies: ["TSMC", "Hyperscaler capex", "Custom accelerator programs"],
    growthDrivers: ["AI semiconductor revenue", "Ethernet scale-up", "VMware margin"],
    risks: ["ASIC customer concentration", "Integration execution", "Networking cycle"],
    metrics: ["AI revenue", "Custom ASIC customers", "Ethernet switching", "Networking demand", "VMware margin", "Hyperscaler capex", "Guidance"],
    goodImpact: [
      { ticker: "TSMC", level: "Direct", note: "custom silicon orders เพิ่ม" },
      { ticker: "GOOGL", level: "Medium", note: "หนุนการขยาย custom accelerators" },
      { ticker: "NVDA", level: "Medium", note: "ยืนยัน AI infrastructure demand แต่แข่งขันกันบางส่วน" },
    ],
    badImpact: [
      { ticker: "TSMC", level: "Direct", note: "ASIC demand อาจชะลอ" },
      { ticker: "GOOGL", level: "Medium", note: "อาจสะท้อนความล่าช้าโครงการ custom silicon" },
    ],
  },
  {
    ticker: "MSFT",
    marketSymbol: "MSFT",
    name: "Microsoft",
    shortName: "Microsoft",
    layer: 4,
    category: "Cloud",
    position: "Cloud and AI Infrastructure",
    summary: "ให้บริการ Azure, Copilot และลงทุนใน AI Infrastructure เชื่อมกับ Enterprise Software",
    revenue: ["Azure", "Microsoft 365", "Server and enterprise software"],
    customers: ["Enterprises", "Developers", "Public sector"],
    dependencies: ["GPU capacity", "Data center power", "Enterprise IT budgets"],
    growthDrivers: ["Azure AI contribution", "Copilot adoption", "Commercial bookings"],
    risks: ["Capex return uncertainty", "Capacity constraints", "Cloud competition"],
    metrics: ["Azure growth", "AI contribution", "Copilot adoption", "Commercial bookings", "Capex", "Data Center capacity", "Operating margin"],
    goodImpact: [
      { ticker: "NVDA", level: "Direct", note: "Azure expansion เพิ่ม GPU demand" },
      { ticker: "PLTR", level: "Medium", note: "หนุน Enterprise AI adoption" },
      { ticker: "ZS", level: "Medium", note: "Cloud adoption เพิ่มพื้นที่การรักษาความปลอดภัย" },
    ],
    badImpact: [
      { ticker: "NVDA", level: "Medium", note: "capex ชะลออาจลดคำสั่ง GPU" },
      { ticker: "PLTR", level: "Medium", note: "Enterprise AI budgets อาจอ่อนลง" },
    ],
  },
  {
    ticker: "GOOGL",
    marketSymbol: "GOOGL",
    name: "Alphabet",
    shortName: "Alphabet",
    layer: 4,
    category: "Cloud",
    position: "Cloud and AI Infrastructure",
    summary: "ให้บริการ Google Cloud, Gemini และนำ AI ไปใช้ใน Search, Ads และ Workspace",
    revenue: ["Search advertising", "Google Cloud", "YouTube advertising"],
    customers: ["Advertisers", "Cloud customers", "Consumers"],
    dependencies: ["Data center capex", "User engagement", "Advertiser demand"],
    growthDrivers: ["Gemini adoption", "Cloud margin", "AI Overviews monetization", "TPU deployment"],
    risks: ["AI disrupts search economics", "Regulation", "High capex"],
    metrics: ["Cloud growth", "Cloud margin", "Search growth", "Gemini adoption", "AI Overviews monetization", "Capex", "TPU deployment"],
    goodImpact: [
      { ticker: "AVGO", level: "Direct", note: "custom accelerator programs และ networking demand" },
      { ticker: "NVDA", level: "Medium", note: "เพิ่ม compute capacity แบบผสม GPU/TPU" },
      { ticker: "PLTR", level: "Medium", note: "Enterprise AI adoption แข็งแรง" },
    ],
    badImpact: [
      { ticker: "AVGO", level: "Medium", note: "custom accelerator spending อาจชะลอ" },
      { ticker: "NVDA", level: "Medium", note: "GPU demand อาจอ่อนลง" },
    ],
  },
  {
    ticker: "AMZN",
    marketSymbol: "AMZN",
    name: "Amazon",
    shortName: "Amazon",
    layer: 4,
    category: "Cloud",
    position: "Cloud and AI Infrastructure",
    summary: "ให้บริการ AWS, Bedrock และพัฒนาชิป Trainium กับ Inferentia",
    revenue: ["AWS", "E-commerce", "Advertising"],
    customers: ["Enterprises", "Developers", "Consumers"],
    dependencies: ["Data center capex", "Cloud workload growth", "Consumer spending"],
    growthDrivers: ["AWS AI workloads", "Bedrock adoption", "Trainium demand"],
    risks: ["Capex intensity", "Cloud competition", "Retail margin volatility"],
    metrics: ["AWS growth", "AWS operating income", "Capex", "AI workload growth", "Bedrock adoption", "Trainium demand", "Advertising revenue"],
    goodImpact: [
      { ticker: "NVDA", level: "Direct", note: "AWS capacity expansion เพิ่ม GPU demand" },
      { ticker: "AVGO", level: "Medium", note: "หนุน networking และ custom silicon" },
      { ticker: "PLTR", level: "Medium", note: "Enterprise AI adoption เพิ่ม" },
    ],
    badImpact: [
      { ticker: "NVDA", level: "Medium", note: "capex ชะลออาจลด GPU demand" },
      { ticker: "AVGO", level: "Medium", note: "networking demand อาจอ่อนลง" },
    ],
  },
  {
    ticker: "PLTR",
    marketSymbol: "PLTR",
    name: "Palantir Technologies",
    shortName: "Palantir",
    layer: 5,
    category: "Software",
    position: "Enterprise AI and Cybersecurity",
    summary: "นำข้อมูลขององค์กรและรัฐบาลมาใช้กับ AI ผ่าน AIP ในกระบวนการทำงานจริง",
    revenue: ["Government contracts", "Commercial subscriptions", "AIP platform"],
    customers: ["US government", "Large enterprises", "Defense organizations"],
    dependencies: ["Cloud infrastructure", "Enterprise AI budgets", "Government procurement"],
    growthDrivers: ["US commercial growth", "AIP adoption", "Customer expansion"],
    risks: ["High valuation", "Stock-based compensation", "Contract concentration"],
    metrics: ["US commercial growth", "Government growth", "Customer count", "Remaining deal value", "AIP adoption", "Operating margin", "Guidance"],
    goodImpact: [
      { ticker: "MSFT", level: "Medium", note: "Enterprise AI workloads อาจใช้ Azure" },
      { ticker: "AMZN", level: "Medium", note: "Enterprise AI workloads อาจใช้ AWS" },
      { ticker: "GOOGL", level: "Indirect", note: "สะท้อน AI adoption ระดับองค์กร" },
      { ticker: "ZS", level: "Medium", note: "AI adoption เพิ่มความต้องการ security" },
    ],
    badImpact: [
      { ticker: "MSFT", level: "Indirect", note: "สัญญาณ Enterprise AI adoption อ่อนลง" },
      { ticker: "ZS", level: "Indirect", note: "งบองค์กรอาจระมัดระวัง" },
    ],
  },
  {
    ticker: "ZS",
    marketSymbol: "ZS",
    name: "Zscaler",
    shortName: "Zscaler",
    layer: 5,
    category: "Software",
    position: "Enterprise AI and Cybersecurity",
    summary: "Cloud Security และ Zero Trust สำหรับผู้ใช้ ระบบ และข้อมูลในยุค AI",
    revenue: ["Subscription security platform", "Zero Trust services", "Data protection"],
    customers: ["Large enterprises", "Public sector", "Cloud-first organizations"],
    dependencies: ["Cloud adoption", "Enterprise security budgets", "Sales execution"],
    growthDrivers: ["Zero Trust adoption", "AI security products", "Large customer growth"],
    risks: ["Competition", "Sales efficiency", "Long deal cycles"],
    metrics: ["ARR", "Billings", "RPO", "Large customer growth", "Zero Trust adoption", "AI security products", "Free cash flow"],
    goodImpact: [
      { ticker: "MSFT", level: "Indirect", note: "Cloud adoption แข็งแรง" },
      { ticker: "AMZN", level: "Indirect", note: "Cloud workload growth แข็งแรง" },
      { ticker: "PLTR", level: "Medium", note: "Enterprise AI spending sentiment ดีขึ้น" },
    ],
    badImpact: [
      { ticker: "PLTR", level: "Medium", note: "อาจสะท้อน Enterprise spending อ่อนลง" },
      { ticker: "MSFT", level: "Indirect", note: "Cloud security budgets อาจชะลอ" },
    ],
  },
  {
    ticker: "AAPL",
    marketSymbol: "AAPL",
    name: "Apple",
    shortName: "Apple",
    layer: 6,
    category: "Consumer",
    position: "Consumer AI and Devices",
    summary: "นำ AI ไปใช้ใน iPhone, Mac, iPad และบริการ เพื่อกระตุ้น upgrade cycle",
    revenue: ["iPhone", "Services", "Mac and iPad"],
    customers: ["Consumers", "Enterprises", "Developers"],
    dependencies: ["TSMC", "Consumer demand", "China supply and demand"],
    growthDrivers: ["Apple Intelligence adoption", "Upgrade cycle", "Services growth"],
    risks: ["AI feature delays", "China demand", "App ecosystem regulation"],
    metrics: ["iPhone sales", "Apple Intelligence adoption", "Services growth", "China revenue", "Gross margin", "Upgrade cycle"],
    goodImpact: [
      { ticker: "TSMC", level: "Direct", note: "คำสั่งผลิตชิปอุปกรณ์เพิ่ม" },
      { ticker: "ASML", level: "Indirect", note: "หนุน advanced-node capacity ระยะยาว" },
      { ticker: "GOOGL", level: "Medium", note: "ผลขึ้นกับข้อตกลง Search และ AI" },
    ],
    badImpact: [
      { ticker: "TSMC", level: "Direct", note: "คำสั่งผลิต mobile chips อาจลด" },
      { ticker: "GOOGL", level: "Medium", note: "ผลขึ้นกับข้อตกลง Search" },
    ],
  },
  {
    ticker: "ISRG",
    marketSymbol: "ISRG",
    name: "Intuitive Surgical",
    shortName: "Intuitive Surgical",
    layer: 7,
    category: "Healthcare",
    position: "Healthcare Technology",
    summary: "ระบบหุ่นยนต์ช่วยผ่าตัด da Vinci พร้อมรายได้ประจำจากเครื่องมือและจำนวนการผ่าตัด",
    revenue: ["Instruments and accessories", "Systems", "Service"],
    customers: ["Hospitals", "Surgery centers", "Healthcare systems"],
    dependencies: ["Hospital capital budgets", "Procedure volumes", "Regulatory approvals"],
    growthDrivers: ["Procedure growth", "da Vinci 5 adoption", "Recurring instruments revenue"],
    risks: ["Hospital budgets", "Regulatory delays", "Robotic surgery competition"],
    metrics: ["Procedure growth", "System placements", "da Vinci 5 adoption", "Recurring revenue", "Gross margin", "Regulatory approvals"],
    goodImpact: [
      { ticker: "ISRG", level: "Direct", note: "บวกจาก procedure และ recurring revenue" },
    ],
    badImpact: [
      { ticker: "ISRG", level: "Direct", note: "กดดัน placements และ recurring revenue" },
    ],
  },
  {
    ticker: "SPCX",
    marketSymbol: "SPCX",
    name: SPCX_CONFIG.companyName,
    shortName: "SpaceX",
    layer: 8,
    category: "Space",
    position: "Satellite and Space Infrastructure",
    status: "Verified",
    warning: SPCX_CONFIG.warning,
    summary: "ผู้ให้บริการ launch, Starlink connectivity และโครงสร้างพื้นฐานอวกาศ โดย Elon Musk เป็น CEO",
    revenue: ["Launch services", "Starlink connectivity", "Government and defense contracts"],
    customers: ["Consumer and enterprise connectivity", "Government agencies", "Commercial launch customers"],
    dependencies: ["Launch cadence", "Starlink deployment", "Capital expenditure", "Spectrum and regulatory approvals"],
    growthDrivers: ["Starlink subscriber growth", "Launch backlog", "Direct-to-cell expansion", "Government demand"],
    risks: ["Capital intensity", "Launch and operational risk", "Regulatory risk", "High valuation sensitivity"],
    metrics: ["Starlink subscriber growth", "Launch cadence", "Launch backlog", "Government contracts", "Capital expenditure", "Free cash flow"],
    goodImpact: [],
    badImpact: [],
  },
];

const layers = [
  { id: 1, title: "Semiconductor Equipment", label: "เครื่องจักร", color: "#a78bfa" },
  { id: 2, title: "Semiconductor Manufacturing", label: "โรงงานผลิต", color: "#38bdf8" },
  { id: 3, title: "AI Chips and Networking", label: "Compute", color: "#22d3ee" },
  { id: 4, title: "Cloud and AI Infrastructure", label: "Cloud", color: "#2dd4bf" },
  { id: 5, title: "Enterprise AI and Cybersecurity", label: "Enterprise", color: "#fbbf24" },
  { id: 6, title: "Consumer AI and Devices", label: "Consumer", color: "#fb923c" },
  { id: 7, title: "Healthcare Technology", label: "Healthcare", color: "#f472b6" },
  { id: 8, title: "Satellite and Space Infrastructure", label: "Space", color: "#94a3b8" },
];

const relationships = [
  { from: "ASML", to: "TSMC", label: "เครื่องจักรผลิตชิป", detail: "ASML ขายเครื่อง EUV สำหรับการผลิตชิปขั้นสูงให้ TSMC", level: "Direct" },
  { from: "TSMC", to: "NVDA", label: "ผลิต GPU + packaging", detail: "TSMC ผลิต GPU และ advanced packaging ให้ NVIDIA", level: "Direct" },
  { from: "TSMC", to: "AVGO", label: "ผลิต custom ASIC", detail: "TSMC ผลิต custom AI chips ที่ Broadcom ออกแบบ", level: "Direct" },
  { from: "TSMC", to: "AAPL", label: "ผลิต Apple silicon", detail: "TSMC ผลิตชิป Apple silicon สำหรับอุปกรณ์ของ Apple", level: "Direct" },
  { from: "NVDA", to: "MSFT", label: "GPU สำหรับ Azure", detail: "Microsoft ซื้อ GPU เพื่อขยาย Azure AI capacity", level: "Direct" },
  { from: "NVDA", to: "GOOGL", label: "GPU สำหรับ Google Cloud", detail: "Alphabet ใช้ NVIDIA GPU ควบคู่กับ TPU ใน Google Cloud", level: "Direct" },
  { from: "NVDA", to: "AMZN", label: "GPU สำหรับ AWS", detail: "AWS ให้บริการ NVIDIA GPU สำหรับ AI workloads", level: "Direct" },
  { from: "AVGO", to: "GOOGL", label: "Custom accelerators", detail: "Broadcom ช่วยออกแบบ custom AI accelerators", level: "Direct" },
  { from: "AVGO", to: "Hyperscalers", label: "Networking + ASIC", detail: "Broadcom ขาย networking chips และ custom ASIC ให้ hyperscalers", level: "Direct" },
  { from: "MSFT", to: "PLTR", label: "Cloud infrastructure", detail: "PLTR ใช้ Cloud Infrastructure เพื่อให้บริการ AIP แก่องค์กร", level: "Medium" },
  { from: "GOOGL", to: "Cloud customers", label: "Cloud + AI Platform", detail: "Google Cloud ให้บริการ compute, data และ Gemini แก่ลูกค้าองค์กร", level: "Direct" },
  { from: "AMZN", to: "AWS customers", label: "AWS + Bedrock", detail: "AWS ให้บริการ AI infrastructure และ foundation models แก่ลูกค้า", level: "Direct" },
  { from: "PLTR", to: "Government + Enterprise", label: "AIP in operations", detail: "Palantir นำ AI ไปใช้ในกระบวนการทำงานของรัฐบาลและองค์กร", level: "Direct" },
  { from: "ZS", to: "Cloud enterprises", label: "Zero Trust", detail: "Zscaler ปกป้องผู้ใช้และข้อมูลขององค์กรที่ใช้ Cloud", level: "Direct" },
  { from: "AAPL", to: "Consumers", label: "AI devices", detail: "Apple นำ AI สู่ผู้บริโภคผ่าน iPhone, Mac และ iPad", level: "Direct" },
  { from: "ISRG", to: "Hospitals", label: "Robotic surgery", detail: "Intuitive Surgical ขายระบบ da Vinci และเครื่องมือให้โรงพยาบาล", level: "Direct" },
  { from: "SPCX", to: "Space customers", label: "Launch + connectivity", detail: "SpaceX ให้บริการ launch, Starlink connectivity และโครงสร้างพื้นฐานอวกาศแก่ลูกค้าภาครัฐและเชิงพาณิชย์", level: "Direct" },
];

const scenarios = [
  {
    id: "asml",
    title: "Scenario A · ASML งบดี",
    tone: "upstream",
    signals: ["Bookings สูงกว่าคาด", "Guidance ดี", "EUV demand แข็งแกร่ง"],
    impacts: ["ASML — บวกโดยตรง", "TSMC — บวกเชิงความเชื่อมั่นต่อกำลังผลิต", "NVDA / AVGO — บวกทางอ้อม", "หุ้นชิปโดยรวม — Sentiment ดีขึ้น"],
    cautions: ["Bookings อาจผันผวนรายไตรมาส", "งบดีแต่ Guidance อ่อน หุ้นอาจลงได้"],
  },
  {
    id: "tsmc",
    title: "Scenario B · TSMC งบดี",
    tone: "upstream",
    signals: ["HPC revenue โต", "AI demand แข็งแรง", "CoWoS capacity เต็ม", "Capex เพิ่ม"],
    impacts: ["TSMC — บวกโดยตรง", "NVDA — บวกจาก GPU demand", "AVGO — บวกจาก ASIC demand", "ASML — โอกาสลงทุนเครื่องจักรเพิ่ม", "AAPL — ขึ้นกับยอดชิปอุปกรณ์"],
    cautions: ["ต้องแยก AI demand ออกจาก smartphone cycle", "Capex สูงอาจกด free cash flow ระยะสั้น"],
  },
  {
    id: "nvda",
    title: "Scenario C · NVIDIA งบดี",
    tone: "compute",
    signals: ["Data Center revenue สูงกว่าคาด", "Blackwell demand แข็งแรง", "Guidance สูง", "Gross margin ดีกว่าคาด"],
    impacts: ["NVDA — บวกโดยตรง", "TSMC — บวกจากคำสั่งผลิต", "ASML — บวกทางอ้อม", "AVGO — อาจบวกตาม sentiment", "Hyperscalers — demand ดี แต่ต้นทุน capex อาจกดดัน"],
    cautions: ["ดูคุณภาพ Guidance และ supply constraints", "ตลาดอาจรับรู้ความคาดหวังสูงไว้แล้ว"],
  },
  {
    id: "capex",
    title: "Scenario D · Hyperscaler Capex เพิ่ม",
    tone: "cloud",
    signals: ["MSFT / GOOGL / AMZN เพิ่มแผนลงทุน", "Data Center capacity เร่ง", "AI workloads โต"],
    impacts: ["NVDA / AVGO — บวก", "TSMC — บวก", "ASML — บวกระยะกลางถึงยาว", "PLTR / ZS — บวกหาก adoption เพิ่ม", "Hyperscalers — ขึ้นหรือลงตาม ROI ที่ตลาดคาด"],
    cautions: ["Capex เพิ่มโดยไม่มีรายได้ตาม อาจกด valuation", "ข้อจำกัดพลังงานและการก่อสร้าง Data Center"],
  },
  {
    id: "pltr",
    title: "Scenario E · Palantir งบดี",
    tone: "software",
    signals: ["Commercial revenue โตสูง", "ลูกค้าใหม่เพิ่ม", "AIP adoption เร่ง", "Guidance สูงขึ้น"],
    impacts: ["PLTR — บวกโดยตรง", "MSFT / AMZN / GOOGL — บวกเล็กน้อย", "NVDA — ผลทางอ้อมค่อนข้างน้อย", "Software AI — Sentiment ดีขึ้น"],
    cautions: ["Valuation sensitivity สูง", "ติดตาม stock-based compensation และ contract mix"],
  },
  {
    id: "apple",
    title: "Scenario F · Apple Intelligence สำเร็จ",
    tone: "consumer",
    signals: ["Adoption สูง", "Upgrade cycle เร็วขึ้น", "Services engagement เพิ่ม"],
    impacts: ["AAPL — บวกจาก Upgrade cycle", "TSMC — บวกจากคำสั่งผลิต", "ASML — บวกทางอ้อมระยะยาว", "GOOGL — ได้หรือเสียตามข้อตกลง Search / AI", "Mobile supply chain — บวก"],
    cautions: ["Feature rollout และคุณภาพผลิตภัณฑ์", "China demand และ regulatory risk"],
  },
  {
    id: "slowdown",
    title: "Scenario G · AI Capex ชะลอ",
    tone: "risk",
    signals: ["Hyperscalers ลด Guidance capex", "Data Center orders เลื่อน", "Utilization ต่ำกว่าคาด"],
    impacts: ["NVDA — ลบมาก", "AVGO / TSMC — ลบ", "ASML — ลบแบบมี Lag", "Hyperscalers — อาจบวกจากต้นทุนลด หรือ ลบจาก demand อ่อน", "PLTR / ZS — ขึ้นกับ Enterprise demand", "AAPL / ISRG — กระทบน้อยกว่า"],
    cautions: ["แยก efficiency gains ออกจาก demand destruction", "ดู duration ของการชะลอและ inventory cycle"],
  },
];

const dependencyMatrix = [
  { company: "ASML", ai: "High", semi: "Very High", enterprise: "Low", consumer: "Medium", valuation: "High", rates: "Medium", geo: "Very High" },
  { company: "TSMC", ai: "Very High", semi: "Very High", enterprise: "Medium", consumer: "High", valuation: "Medium", rates: "Medium", geo: "Very High" },
  { company: "NVDA", ai: "Very High", semi: "Very High", enterprise: "High", consumer: "Low", valuation: "Very High", rates: "High", geo: "High" },
  { company: "AVGO", ai: "Very High", semi: "High", enterprise: "High", consumer: "Low", valuation: "High", rates: "High", geo: "Medium" },
  { company: "MSFT", ai: "High", semi: "Low", enterprise: "Very High", consumer: "Medium", valuation: "High", rates: "High", geo: "Medium" },
  { company: "GOOGL", ai: "High", semi: "Low", enterprise: "High", consumer: "High", valuation: "High", rates: "High", geo: "Medium" },
  { company: "AMZN", ai: "High", semi: "Low", enterprise: "High", consumer: "High", valuation: "High", rates: "High", geo: "Low" },
  { company: "PLTR", ai: "Medium", semi: "Low", enterprise: "Very High", consumer: "Low", valuation: "Very High", rates: "Very High", geo: "Medium" },
  { company: "ZS", ai: "Medium", semi: "Low", enterprise: "Very High", consumer: "Low", valuation: "High", rates: "Very High", geo: "Low" },
  { company: "AAPL", ai: "Medium", semi: "High", enterprise: "Low", consumer: "Very High", valuation: "High", rates: "High", geo: "High" },
  { company: "ISRG", ai: "Low", semi: "Low", enterprise: "Medium", consumer: "Medium", valuation: "High", rates: "High", geo: "Medium" },
  { company: "SPCX", ai: "Unknown", semi: "Unknown", enterprise: "Unknown", consumer: "Unknown", valuation: "Unknown", rates: "Unknown", geo: "Unknown" },
];

window.AI_CHAIN_DATA = Object.freeze({
  spcxConfig: SPCX_CONFIG,
  companies,
  layers,
  relationships,
  scenarios,
  dependencyMatrix,
});
